export const ALL_CALLBACK_REQUEST = "ALL_CALLBACK_REQUEST";
export const ALL_CALLBACK_SUCCESS = "ALL_CALLBACK_SUCCESS";
export const ALL_CALLBACK_FAIL = "ALL_CALLBACK_FAIL";

export const NEW_CALLBACK_REQUEST = "NEW_CALLBACK_REQUEST";
export const NEW_CALLBACK_SUCCESS = "NEW_CALLBACK_SUCCESS";
export const NEW_CALLBACK_RESET = "NEW_CALLBACK_RESET";
export const NEW_CALLBACK_FAIL = "NEW_CALLBACK_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const DELETE_CALLBACK_REQUEST = "DELETE_CALLBACK_REQUEST";
export const DELETE_CALLBACK_SUCCESS = "DELETE_CALLBACK_SUCCESS";
export const DELETE_CALLBACK_RESET = "DELETE_CALLBACK_RESET";
export const DELETE_CALLBACK_FAIL = "DELETE_CALLBACK_FAIL";

export const ADMIN_CALLBACK_REQUEST = "ADMIN_CALLBACK_REQUEST";
export const ADMIN_CALLBACK_SUCCESS = "ADMIN_CALLBACK_SUCCESS";
export const ADMIN_CALLBACK_FAIL = "ADMIN_CALLBACK_FAIL";
