export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const ADD_TO_ORDER = "ADD_TO_ORDER";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const ADD_TO_COMPARE = "ADD_TO_COMPARE";
export const REMOVE_FROM_COMPARE = "REMOVE_FROM_COMPARE";
export const EMPTY_COMPARE = "EMPTY_COMPARE";
