export const ALL_KNOWLEDGES_REQUEST = "ALL_KNOWLEDGES_REQUEST";
export const ALL_KNOWLEDGES_SUCCESS = "ALL_KNOWLEDGES_SUCCESS";
export const ALL_KNOWLEDGES_FAIL = "ALL_KNOWLEDGES_FAIL";

export const NEW_KNOWLEDGE_REQUEST = "NEW_KNOWLEDGE_REQUEST";
export const NEW_KNOWLEDGE_SUCCESS = "NEW_KNOWLEDGE_SUCCESS";
export const NEW_KNOWLEDGE_RESET = "NEW_KNOWLEDGE_RESET";
export const NEW_KNOWLEDGE_FAIL = "NEW_KNOWLEDGE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
