export const ALL_ORDERCALLBACK_REQUEST = "ALL_ORDERCALLBACK_REQUEST";
export const ALL_ORDERCALLBACK_SUCCESS = "ALL_ORDERCALLBACK_SUCCESS";
export const ALL_ORDERCALLBACK_FAIL = "ALL_ORDERCALLBACK_FAIL";

export const NEW_ORDERCALLBACK_REQUEST = "NEW_ORDERCALLBACK_REQUEST";
export const NEW_ORDERCALLBACK_SUCCESS = "NEW_ORDERCALLBACK_SUCCESS";
export const NEW_ORDERCALLBACK_RESET = "NEW_ORDERCALLBACK_RESET";
export const NEW_ORDERCALLBACK_FAIL = "NEW_ORDERCALLBACK_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const DELETE_ORDERCALLBACK_REQUEST = "DELETE_ORDERCALLBACK_REQUEST";
export const DELETE_ORDERCALLBACK_SUCCESS = "DELETE_ORDERCALLBACK_SUCCESS";
export const DELETE_ORDERCALLBACK_RESET = "DELETE_ORDERCALLBACK_RESET";
export const DELETE_ORDERCALLBACK_FAIL = "DELETE_ORDERCALLBACK_FAIL";

export const ADMIN_ORDERCALLBACK_REQUEST = "ADMIN_ORDERCALLBACK_REQUEST";
export const ADMIN_ORDERCALLBACK_SUCCESS = "ADMIN_ORDERCALLBACK_SUCCESS";
export const ADMIN_ORDERCALLBACK_FAIL = "ADMIN_ORDERCALLBACK_FAIL";
