export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const ALL_COMPARISION_REQUEST = "ALL_COMPARISION_REQUEST";
export const ALL_COMPARISION_SUCCESS = "ALL_COMPARISION_SUCCESS";
export const ALL_COMPARISION_FAIL = "ALL_COMPARISION_FAIL";

export const ALL_INSIGHTS_REQUEST = "ALL_INSIGHTS_REQUEST";
export const ALL_INSIGHTS_SUCCESS = "ALL_INSIGHTS_SUCCESS";
export const ALL_INSIGHTS_FAIL = "ALL_INSIGHTS_FAIL";

export const ALL_CROPS_REQUEST = "ALL_CROPS_REQUEST";
export const ALL_CROPS_SUCCESS = "ALL_CROPS_SUCCESS";
export const ALL_CROPS_FAIL = "ALL_CROPS_FAIL";

export const PRODUCT_DETAILSBYSLUG_REQUEST = "PRODUCT_DETAILSBYSLUG_REQUEST";
export const PRODUCT_DETAILSBYSLUG_SUCCESS = "PRODUCT_DETAILSBYSLUG_SUCCESS";
export const PRODUCT_DETAILSBYSLUG_FAIL = "PRODUCT_DETAILSBYSLUG_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CROP_DETAILS_REQUEST = "CROP_DETAILS_REQUEST";
export const CROP_DETAILS_SUCCESS = "CROP_DETAILS_SUCCESS";
export const CROP_DETAILS_FAIL = "CROP_DETAILS_FAIL";

export const INSIGHT_DETAILS_REQUEST = "INSIGHT_DETAILS_REQUEST";
export const INSIGHT_DETAILS_SUCCESS = "INSIGHT_DETAILS_SUCCESS";
export const INSIGHT_DETAILS_FAIL = "INSIGHT_DETAILS_FAIL";

export const COMPARE_DETAILS_REQUEST = "COMPARE_DETAILS_REQUEST";
export const COMPARE_DETAILS_SUCCESS = "COMPARE_DETAILS_SUCCESS";
export const COMPARE_DETAILS_FAIL = "COMPARE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST";
export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCTS_SUCCESS";
export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCTS_FAIL";

export const ADMIN_CROPS_REQUEST = "ADMIN_CROPS_REQUEST";
export const ADMIN_CROPS_SUCCESS = "ADMIN_CROPS_SUCCESS";
export const ADMIN_CROPS_FAIL = "ADMIN_CROPS_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const NEW_CROP_REQUEST = "NEW_CROP_REQUEST";
export const NEW_CROP_SUCCESS = "NEW_CROP_SUCCESS";
export const NEW_CROP_RESET = "NEW_CROP_RESET";
export const NEW_CROP_FAIL = "NEW_CROP_FAIL";

export const NEW_COMPARISION_REQUEST = "NEW_COMPARISION_REQUEST";
export const NEW_COMPARISION_SUCCESS = "NEW_COMPARISION_SUCCESS";
export const NEW_COMPARISION_RESET = "NEW_COMPARISION_RESET";
export const NEW_COMPARISION_FAIL = "NEW_COMPARISION_FAIL";

export const NEW_INSIGHTS_REQUEST = "NEW_INSIGHTS_REQUEST";
export const NEW_INSIGHTS_SUCCESS = "NEW_INSIGHTS_SUCCESS";
export const NEW_INSIGHTS_RESET = "NEW_INSIGHTS_RESET";
export const NEW_INSIGHTS_FAIL = "NEW_INSIGHTS_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const UPDATE_CROP_REQUEST = "UPDATE_CROP_REQUEST";
export const UPDATE_CROP_SUCCESS = "UPDATE_CROP_SUCCESS";
export const UPDATE_CROP_RESET = "UPDATE_CROP_RESET";
export const UPDATE_CROP_FAIL = "UPDATE_CROP_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const DELETE_CROP_REQUEST = "DELETE_CROP_REQUEST";
export const DELETE_CROP_SUCCESS = "DELETE_CROP_SUCCESS";
export const DELETE_CROP_RESET = "DELETE_CROP_RESET";
export const DELETE_CROP_FAIL = "DELETE_CROP_FAIL";

export const ALL_REVIEWS_REQUEST = "ALL_REVIEWS_REQUEST";
export const ALL_REVIEWS_SUCCESS = "ALL_REVIEWS_SUCCESS";
export const ALL_REVIEWS_FAIL = "ALL_REVIEWS_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const SLIDER_PRODUCTS_REQUEST = "SLIDER_PRODUCTS_REQUEST";
export const SLIDER_PRODUCTS_SUCCESS = "SLIDER_PRODUCTS_SUCCESS";
export const SLIDER_PRODUCTS_FAIL = "SLIDER_PRODUCTS_FAIL";

export const REMOVE_PRODUCT_DETAILS = "REMOVE_PRODUCT_DETAILS";
export const REMOVE_CROP_DETAILS = "REMOVE_CROP_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
